server:
  port: 9001

# Eureka에 등록될 서비스 이름
spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # 유레카 서버에 등록할 URL
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}